module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/__tests__'],
  testMatch: ['**/__tests__/**/*.test.ts'],
  collectCoverageFrom: ['src/**/*.ts'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@rgs/core$': '<rootDir>/core/src/index.ts',
    '^@rgs/core/(.*)$': '<rootDir>/core/src/$1',
    '^@rgs/storage$': '<rootDir>/storage/src/index.ts',
    '^@rgs/storage/(.*)$': '<rootDir>/storage/src/$1',
    '^@rgs/utils$': '<rootDir>/utils/src/index.ts',
    '^@rgs/utils/(.*)$': '<rootDir>/utils/src/$1',
    '^@rgs/scraper-reddit$': '<rootDir>/scrapers/reddit/src/index.ts',
    '^@rgs/scraper-reddit/(.*)$': '<rootDir>/scrapers/reddit/src/$1',
    '^@rgs/analysis-sentiment$': '<rootDir>/analysis/sentiment/src/index.ts',
    '^@rgs/analysis-sentiment/(.*)$': '<rootDir>/analysis/sentiment/src/$1',
    '^@rgs/analysis-themes$': '<rootDir>/analysis/themes/src/index.ts',
    '^@rgs/analysis-themes/(.*)$': '<rootDir>/analysis/themes/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup.ts'],
};
